import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Learning Next.js",
    template: "%s | Purna learning next.js",
  },
  description: "Generated by Next.js",

}

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h2>Header</h2>
        </header>
        {children}
        
        <footer>
          <h2>Footer</h2>
        </footer>
        
        </body>
    </html>
  )
}

