import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Blogs",
  description: "Generated by Next.js",
};

const page = () => {
  return (
    <div>
      <h2>My Blogs</h2>
    </div>
  );
};

export default page;
